# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 569)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 139, 581, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.v18_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.v18_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v18_Button.sizePolicy().hasHeightForWidth())
        self.v18_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.v18_Button.setFont(font)
        self.v18_Button.setCheckable(True)
        self.v18_Button.setObjectName("v18_Button")
        self.horizontalLayout.addWidget(self.v18_Button)
        self.v22_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.v22_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v22_Button.sizePolicy().hasHeightForWidth())
        self.v22_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.v22_Button.setFont(font)
        self.v22_Button.setCheckable(True)
        self.v22_Button.setObjectName("v22_Button")
        self.horizontalLayout.addWidget(self.v22_Button)
        self.v26_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.v26_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v26_Button.sizePolicy().hasHeightForWidth())
        self.v26_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.v26_Button.setFont(font)
        self.v26_Button.setCheckable(True)
        self.v26_Button.setObjectName("v26_Button")
        self.horizontalLayout.addWidget(self.v26_Button)
        self.v30_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.v30_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v30_Button.sizePolicy().hasHeightForWidth())
        self.v30_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.v30_Button.setFont(font)
        self.v30_Button.setCheckable(True)
        self.v30_Button.setObjectName("v30_Button")
        self.horizontalLayout.addWidget(self.v30_Button)
        self.v34_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.v34_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v34_Button.sizePolicy().hasHeightForWidth())
        self.v34_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.v34_Button.setFont(font)
        self.v34_Button.setCheckable(True)
        self.v34_Button.setObjectName("v34_Button")
        self.horizontalLayout.addWidget(self.v34_Button)
        self.voltage_write_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.voltage_write_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voltage_write_Button.sizePolicy().hasHeightForWidth())
        self.voltage_write_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.voltage_write_Button.setFont(font)
        self.voltage_write_Button.setCheckable(True)
        self.voltage_write_Button.setObjectName("voltage_write_Button")
        self.horizontalLayout.addWidget(self.voltage_write_Button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(140, 249, 581, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.r_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.r_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r_Button.sizePolicy().hasHeightForWidth())
        self.r_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.r_Button.setFont(font)
        self.r_Button.setCheckable(True)
        self.r_Button.setObjectName("r_Button")
        self.horizontalLayout_2.addWidget(self.r_Button)
        self.ry_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.ry_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ry_Button.sizePolicy().hasHeightForWidth())
        self.ry_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.ry_Button.setFont(font)
        self.ry_Button.setCheckable(True)
        self.ry_Button.setObjectName("ry_Button")
        self.horizontalLayout_2.addWidget(self.ry_Button)
        self.yg_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.yg_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yg_Button.sizePolicy().hasHeightForWidth())
        self.yg_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.yg_Button.setFont(font)
        self.yg_Button.setCheckable(True)
        self.yg_Button.setObjectName("yg_Button")
        self.horizontalLayout_2.addWidget(self.yg_Button)
        self.g_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.g_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_Button.sizePolicy().hasHeightForWidth())
        self.g_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.g_Button.setFont(font)
        self.g_Button.setCheckable(True)
        self.g_Button.setObjectName("g_Button")
        self.horizontalLayout_2.addWidget(self.g_Button)
        self.charge_write_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.charge_write_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charge_write_Button.sizePolicy().hasHeightForWidth())
        self.charge_write_Button.setSizePolicy(sizePolicy)
        self.charge_write_Button.setMinimumSize(QtCore.QSize(0, 0))
        self.charge_write_Button.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.charge_write_Button.setFont(font)
        self.charge_write_Button.setCheckable(True)
        self.charge_write_Button.setObjectName("charge_write_Button")
        self.horizontalLayout_2.addWidget(self.charge_write_Button)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(139, 350, 581, 101))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.argu_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.argu_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.argu_Button.sizePolicy().hasHeightForWidth())
        self.argu_Button.setSizePolicy(sizePolicy)
        self.argu_Button.setMaximumSize(QtCore.QSize(116, 79))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.argu_Button.setFont(font)
        self.argu_Button.setCheckable(True)
        self.argu_Button.setObjectName("argu_Button")
        self.horizontalLayout_3.addWidget(self.argu_Button)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.current_write_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.current_write_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_write_Button.sizePolicy().hasHeightForWidth())
        self.current_write_Button.setSizePolicy(sizePolicy)
        self.current_write_Button.setMinimumSize(QtCore.QSize(5, 49))
        self.current_write_Button.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.current_write_Button.setFont(font)
        self.current_write_Button.setCheckable(True)
        self.current_write_Button.setObjectName("current_write_Button")
        self.horizontalLayout_3.addWidget(self.current_write_Button)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 90, 94, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.voltage_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.voltage_radioButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voltage_radioButton.sizePolicy().hasHeightForWidth())
        self.voltage_radioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.voltage_radioButton.setFont(font)
        self.voltage_radioButton.setCheckable(True)
        self.voltage_radioButton.setChecked(False)
        self.voltage_radioButton.setObjectName("voltage_radioButton")
        self.verticalLayout.addWidget(self.voltage_radioButton)
        self.charge_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.charge_radioButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charge_radioButton.sizePolicy().hasHeightForWidth())
        self.charge_radioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.charge_radioButton.setFont(font)
        self.charge_radioButton.setObjectName("charge_radioButton")
        self.verticalLayout.addWidget(self.charge_radioButton)
        self.current_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.current_radioButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_radioButton.sizePolicy().hasHeightForWidth())
        self.current_radioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.current_radioButton.setFont(font)
        self.current_radioButton.setObjectName("current_radioButton")
        self.verticalLayout.addWidget(self.current_radioButton)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 20, 431, 92))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.open_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_Button.sizePolicy().hasHeightForWidth())
        self.open_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.open_Button.setFont(font)
        self.open_Button.setAutoFillBackground(False)
        self.open_Button.setObjectName("open_Button")
        self.gridLayout.addWidget(self.open_Button, 0, 1, 1, 1)
        self.port_Box = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_Box.sizePolicy().hasHeightForWidth())
        self.port_Box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.port_Box.setFont(font)
        self.port_Box.setObjectName("port_Box")
        self.port_Box.addItem("")
        self.port_Box.addItem("")
        self.port_Box.addItem("")
        self.port_Box.addItem("")
        self.port_Box.addItem("")
        self.port_Box.addItem("")
        self.port_Box.addItem("")
        self.port_Box.addItem("")
        self.port_Box.addItem("")
        self.port_Box.addItem("")
        self.gridLayout.addWidget(self.port_Box, 1, 0, 1, 1)
        self.close_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.close_Button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_Button.sizePolicy().hasHeightForWidth())
        self.close_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.close_Button.setFont(font)
        self.close_Button.setObjectName("close_Button")
        self.gridLayout.addWidget(self.close_Button, 1, 1, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setScaledContents(False)
        self.label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_1.setWordWrap(False)
        self.label_1.setOpenExternalLinks(False)
        self.label_1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(51, 50, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lift_Button = QtWidgets.QPushButton(self.centralwidget)
        self.lift_Button.setEnabled(False)
        self.lift_Button.setGeometry(QtCore.QRect(260, 450, 146, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lift_Button.sizePolicy().hasHeightForWidth())
        self.lift_Button.setSizePolicy(sizePolicy)
        self.lift_Button.setMaximumSize(QtCore.QSize(150, 79))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lift_Button.setFont(font)
        self.lift_Button.setCheckable(True)
        self.lift_Button.setObjectName("lift_Button")
        self.right_Button = QtWidgets.QPushButton(self.centralwidget)
        self.right_Button.setEnabled(False)
        self.right_Button.setGeometry(QtCore.QRect(490, 450, 150, 79))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_Button.sizePolicy().hasHeightForWidth())
        self.right_Button.setSizePolicy(sizePolicy)
        self.right_Button.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.right_Button.setFont(font)
        self.right_Button.setCheckable(True)
        self.right_Button.setObjectName("right_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 32))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "三合一仪表上位机"))
        self.v18_Button.setText(_translate("MainWindow", "18v"))
        self.v22_Button.setText(_translate("MainWindow", "22v"))
        self.v26_Button.setText(_translate("MainWindow", "26v"))
        self.v30_Button.setText(_translate("MainWindow", "30v"))
        self.v34_Button.setText(_translate("MainWindow", "34v"))
        self.voltage_write_Button.setText(_translate("MainWindow", "保存参数"))
        self.r_Button.setText(_translate("MainWindow", "红色始端"))
        self.ry_Button.setText(_translate("MainWindow", "红黄相接"))
        self.yg_Button.setText(_translate("MainWindow", "黄绿相接"))
        self.g_Button.setText(_translate("MainWindow", "绿色末端"))
        self.charge_write_Button.setText(_translate("MainWindow", "保存参数"))
        self.argu_Button.setText(_translate("MainWindow", "电流参数"))
        self.current_write_Button.setText(_translate("MainWindow", "保存参数"))
        self.voltage_radioButton.setText(_translate("MainWindow", "电压"))
        self.charge_radioButton.setText(_translate("MainWindow", "荷电"))
        self.current_radioButton.setText(_translate("MainWindow", "电流"))
        self.open_Button.setText(_translate("MainWindow", "开启串口"))
        self.port_Box.setCurrentText(_translate("MainWindow", "/dev/ttyUSB0"))
        self.port_Box.setItemText(0, _translate("MainWindow", "/dev/ttyUSB0"))
        self.port_Box.setItemText(1, _translate("MainWindow", "COM1"))
        self.port_Box.setItemText(2, _translate("MainWindow", "COM2"))
        self.port_Box.setItemText(3, _translate("MainWindow", "COM3"))
        self.port_Box.setItemText(4, _translate("MainWindow", "COM4"))
        self.port_Box.setItemText(5, _translate("MainWindow", "COM5"))
        self.port_Box.setItemText(6, _translate("MainWindow", "COM6"))
        self.port_Box.setItemText(7, _translate("MainWindow", "COM7"))
        self.port_Box.setItemText(8, _translate("MainWindow", "COM8"))
        self.port_Box.setItemText(9, _translate("MainWindow", "COM9"))
        self.close_Button.setText(_translate("MainWindow", "关闭串口"))
        self.label_1.setText(_translate("MainWindow", "串口选择"))
        self.label.setText(_translate("MainWindow", "串口"))
        self.lift_Button.setText(_translate("MainWindow", "参数加"))
        self.right_Button.setText(_translate("MainWindow", "参数减"))

